package: ydeploy
version: '0.1-dev'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum/

requires:
    redaxo: ^5.4.0-dev

config:
    fixtures:
        tables:
            article: ~
            config:
                - { namespace: core }
                - { namespace: mblock }
                - { namespace: media_manager }
                - { namespace: mform }
                - { namespace: sprog }
            markitup_profiles: ~
            media_manager_type: ~
            media_manager_type_effect: ~
            metainfo_field: ~
            metainfo_type: ~
            module_action: ~
            redactor2_profiles: ~
            yform_field: ~
            yform_table: ~
